---
creation_rules:
  - path_regex: .*\.tfvars
    encrypted_regex: '((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))'
    pgp: >-
      CA884EABD6B220A791FF22D8DF099FFFAEB19845,
      A54D8FB506C103352E67737587CB975CFF2E7D8F
