---
version: '3'

tasks:
  default:
    cmds:
      - task --list

  lint:
    desc: lint files
    cmds:
      - yamllint -c '.github/lint/.yamllint.yml' . || true
      - markdownlint -c '.github/lint/.markdownlint.yml' *.md **/*.md .github/**/*.md || true
      - prettier --ignore-path '.github/lint/.prettierignore' --config '.github/lint/.prettierrc.yml' --check . || true
      - tflint --loglevel=info . || true
      - terraform fmt -check -recursive -diff || true

  pretty:
    desc: fix errors
    cmds:
      - prettier --ignore-path '.github/lint/.prettierignore' --config '.github/lint/.prettierrc.yml' --list-different --ignore-unknown --parser=markdown --write '*.md' '**/*.md' || true
      - prettier --ignore-path '.github/lint/.prettierignore' --config '.github/lint/.prettierrc.yml' --list-different --ignore-unknown --parser=yaml --write '*.y*ml' '**/*.y*ml' || true
      - terraform fmt -recursive || true

  security:
    desc: no leaks please
    cmds:
      - talisman --scan || true
      - terrascan scan || true

  pre-commit:
    desc: run pre-commit verbosely
    cmds:
      - pre-commit run --all-files
